<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spec.js</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\bfunction\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>Jasmine</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(afterEach|beforeEach|describe|expect|it|runs|spyOn|waits|waitsFor|xdescribe|xit)\b</string>
			<key>name</key>
			<string>support.function.js.jasmine</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(andCallFake|andCallThrough|andReturn|any|calls|createSpy|execute|getEnv|log|not|reset|toBe|toBeCloseTo|toBeDefined|toBeFalsy|toBeGreaterThan|toBeLessThan|toBeNull|toBeTruthy|toBeUndefined|toContain|toEqual|toHaveBeenCalled|toHaveBeenCalledWith|toMatch|toThrow|tick|useMock)\b</string>
			<key>name</key>
			<string>support.function.js.jasmine</string>
		</dict>
		<dict>
		  <key>match</key>
		  <string>specFilter</string>
		  <key>name</key>
		  <string>entíty.name.function.js.jasmine</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(Clock|jasmine)\b</string>
			<key>name</key>
			<string>support.class.js.jasmine</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.jasmine</string>
	<key>uuid</key>
	<string>EE325085-860E-4442-AE0C-643F6ACEF009</string>
</dict>
</plist>
